# Generated by Django 4.2.9 on 2024-01-17 19:40

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('password', models.CharField(max_length=128)),
                ('role', models.SmallIntegerField(choices=[(0, 'Batsman '), (1, 'Bowler '), (2, 'Coach'), (3, 'Wicketkeeper'), (4, 'Mentor')], default=1, null=True)),
            ],
        ),
    ]
