# Generated by Django 4.2.9 on 2024-01-17 19:56

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Survey',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('scheduled_date', models.DateField()),
                ('scheduled_time', models.TimeField()),
                ('invitations_send_flag', models.SmallIntegerField(choices=[(0, 'yes '), (1, 'no ')], default=1, null=True)),
                ('notification_send_flag', models.SmallIntegerField(choices=[(0, 'yes '), (1, 'no ')], default=1, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_surveys', to='app.user')),
                ('target_users', models.ManyToManyField(related_name='targeted_surveys', to='app.user')),
            ],
        ),
    ]
